add validation for form
olesyaprivat/react_test pull request #1
Opened 2022-02-03 12:25 UTC by olesyaprivat

2022-02-03 13:56 UTC, sologubd requested changes

2022-02-03 13:56 UTC, sologubd commented on src/components/CreateForm.jsx
> +        return maxLengthContent <= (content && content.length) ? true : false;
Думаю перевірку можна спростити до 
`return maxLengthContent <= content.length;`

Оскольки
- порівняння `maxLengthContent <= (content && content.length)` вже дає boolean і нема необхідності в `true : false`
- не потрібно перевіряти `content` оскільки в `const [content, setContent] = useState ('');` задається пуста строка

2022-02-03 13:56 UTC, sologubd commented on src/App.js
> +      isActiveForm ? <CreateForm maxLengthTitle={100} maxLengthContent={1000} createPost={createPost} savePost={savePost} post={activePost} cancelForm={cancelForm}/>
Мінорний коментар
Я б дав назву яка б казале що саме буде створювати форма
наприклад `NoteFrom` | `ArticleFrom` | `CreateNoteFrom` | `CreateArticleFrom` 
або `PostForm` | `CreatePostForm` бо я бачу що нижче використовується назва `Post` але я б подумав. оскільки `post` може тлумачитися як "відправити" або як HTTP метод

2022-02-03 13:56 UTC, sologubd commented on src/components/CreateForm.jsx
> +                    {isShowContentError ? <span className="text-danger">Note text exceeded by {content.length - maxLengthContent} characters</span> : ''}
Мінорний комент 
Як на мене лаконічніше виглядає

```
{isShowContentError && (
  <span className="text-danger">
    Note text exceeded by {content.length - maxLengthContent} characters
  </span>
)}
```

2022-02-03 13:56 UTC, sologubd commented on src/components/CreateForm.jsx
> +                <button disabled={!title || content.length >= 1000} className='btn btn-primary' onClick={isEdit ? save : addPost}>{isEdit ? 'Save' : 'Create'}</button>
Мінорний комент 
Як на мене лаконічніше виглядає

```
{isShowContentError && (
  <span className="text-danger">
    Note text exceeded by {content.length - maxLengthContent} characters
  </span>
)}
```

2022-02-03 14:38 UTC, sologubd commented on src/components/CreateForm.jsx
> +        return maxLengthContent <= (content && content.length) ? true : false;
Доречі 
вираз `maxLengthContent <= (content && content.length)` достаньо небепечний як на мене
Оскільки `(content && content.length)` молже повертати різні типи значення в залежності від того яке значення буде в `content`. І не всі порівняння з `maxLengthContent` можуть дати непередбачувані результати

2022-02-04 09:08 UTC, olesyaprivat commented on src/components/CreateForm.jsx
> +        return maxLengthContent <= (content && content.length) ? true : false;
Дякую, пофіксила

2022-02-04 09:09 UTC, olesyaprivat commented on src/App.js
> +      isActiveForm ? <CreateForm maxLengthTitle={100} maxLengthContent={1000} createPost={createPost} savePost={savePost} post={activePost} cancelForm={cancelForm}/>
Поки що не змінювала назву, в наступній домашці зміню, параметри занесла в форму

2022-02-04 09:10 UTC, olesyaprivat commented on src/components/CreateForm.jsx
> +                    {isShowContentError ? <span className="text-danger">Note text exceeded by {content.length - maxLengthContent} characters</span> : ''}
дякую, змінила

2022-02-04 09:11 UTC, olesyaprivat commented on src/components/CreateForm.jsx
> +                <button disabled={!title || content.length >= 1000} className='btn btn-primary' onClick={isEdit ? save : addPost}>{isEdit ? 'Save' : 'Create'}</button>
дякую, змінила

2022-02-08 22:14 UTC, Rastopyr requested changes

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
>      const isShowError = useMemo(()=> {
isTitleValid

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
> +    const isShowContentError = useMemo(()=> {
isContentValid

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
> +                <button disabled={!title || content.length >= 1000} className='btn btn-primary' onClick={isEdit ? save : addPost}>{isEdit ? 'Save' : 'Create'}</button>
Тут дублируется логика валидации. В аттрибуте disabled лучше использовать уже ранее посчитанные значения валидности контента.

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
>                      <input maxLength={maxLengthTitle} value={title || ''} onChange={e => setTitle(e.target.value)} type="text" className='form-control'/>
В `value` в любом случае будет или значение или пустая строка, оператор ||  лишний

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
>                      <textarea  value={content} onChange={e => setContent(e.target.value)} type="text" onKeyPress={handleKeyPress} className='form-control'></textarea>
Для того чтобы проще было читать jsx, то лучше при большом количестве аттрибутов, переносить каждый на новую строку. А сами аттрибуты стараться сортировать "лесенкой"

```
<textarea 
  type="text" 
  value={content}
  className='form-control'
  onChange={e => setContent(e.target.value)}
  onKeyPress={handleKeyPress}
/>
```

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
> +                <button disabled={!title || content.length >= 1000} className='btn btn-primary' onClick={isEdit ? save : addPost}>{isEdit ? 'Save' : 'Create'}</button>
Лучше минимально писать логики или выражений в аттрибутах, а стараться выносить такие выражения в переменные

2022-02-08 22:14 UTC, Rastopyr commented on src/components/CreateForm.jsx
> +const CreateForm = function ({createPost, savePost, post, cancelForm}) {
У компонента получается очень императивный контракт. Лучше чтобы проспы говорили про поведение компонента.

`createPost` -> `onCreate`
`savePost` -> `onSave`
`cancelForm` -> `onCancel`

2022-02-10 16:24 UTC, merged